# Generated by Django 4.2.4 on 2023-08-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='is_publish'),
        ),
        migrations.AddField(
            model_name='new',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='is_publish'),
        ),
    ]
