# Generated by Django 4.2.4 on 2023-09-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_blogcategory_newcategory_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='blog', to='pages.blogcategory', verbose_name='category'),
        ),
    ]
