# Generated by Django 4.2.4 on 2023-09-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ManyToManyField(related_name='new', to='pages.newcategory', verbose_name='category'),
        ),
    ]
