# Generated by Django 4.2.4 on 2023-08-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='fullname')),
                ('company_role', models.CharField(max_length=100, verbose_name='company_role')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('linkdin_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='linkdin_id')),
                ('whatsapp_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='whatsapp_number')),
                ('profile_photo', models.ImageField(upload_to='member_profile/', verbose_name='profile_photo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'Team_Member',
                'verbose_name_plural': 'Team_Members',
            },
        ),
    ]
