# Generated by Django 4.2.4 on 2023-08-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='company_name')),
                ('address', models.TextField(verbose_name='address')),
                ('phone_number', models.CharField(max_length=11, verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('linkdin_id', models.CharField(max_length=40, verbose_name='')),
                ('instagram_id', models.CharField(max_length=40, verbose_name='')),
                ('whatsapp_number', models.CharField(max_length=10, verbose_name='')),
                ('telegram_id', models.CharField(max_length=40, verbose_name='')),
                ('eita_id', models.CharField(max_length=40, verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUs',
            },
        ),
    ]
