# Generated by Django 4.2.4 on 2023-08-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_aboutus_logo_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='eita_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='linkdin_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
    ]
