# Generated by Django 4.2.4 on 2023-08-29 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_aboutus_eita_id_alter_aboutus_instagram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='eita_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='eita_id'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='instagram_id'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='linkdin_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='linkdin_id'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='telegram_id'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='whatsapp_number'),
        ),
    ]
