# Generated by Django 4.2.4 on 2023-08-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_contactus_show_as_client_think'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_Choose_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'Why_Choose_Us',
                'verbose_name_plural': 'Why_Choose_Us',
            },
        ),
    ]
