# Generated by Django 4.2.4 on 2023-08-30 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='user',
        ),
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='fullname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='fullname'),
            preserve_default=False,
        ),
    ]
