# Generated by Django 4.2.4 on 2023-08-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_remove_contactus_user_contactus_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Work_Together',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='company_name')),
                ('company_logo', models.ImageField(upload_to='other_companies_logo/', verbose_name='company_logo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'Company_Work_Together',
                'verbose_name_plural': 'Companies_Work_Together',
            },
        ),
    ]
